<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-5Q610K75" failures="1" tests="1" name="Test2" time="6.946" errors="0" timestamp="2023-05-07T11:33:26 CEST">
  <testcase classname="com.saucedemo.ShoppingCartTest" name="numbersOfItem" time="0.993">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.saucedemo.ShoppingCartTest.numbersOfItem(ShoppingCartTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- numbersOfItem -->
</testsuite> <!-- Test2 -->
